### PR TITLE
Fix #460: Add type hints for extern inference

### LINKED ISSUE #460: 0.9.0-rc1 TypeError: Cannot read property '$argv$' of undefined
This happening when compile with `:advanced`. It works during developing `clj -A:fig:build`, because no `:advanced` compilation.

Reagent version:
`reagent {:mvn/version "0.9.0-rc1" :exclusions [cljsjs/react cljsjs/react-dom]}`

It works with:
`reagent {:mvn/version "0.8.1" :exclusions [cljsjs/react cljsjs/react-dom]}`

image

Error:
```
git clone -b doc git@github.com:kwladyka/form-validator-cljs.git doc
cd doc
git checkout a81d4bc574cbab68e67a791db118e44f373e3217
# add `:pseudo-names true` to `dev.cljs.edn`
npm i
npx webpack --mode=production
clojure -A:fig:min
cp resources/public/index.html target/public/
cp -r resources/public/css target/public/
```

Then open `target/public/index.html` to see the issue.

Temporary solution: downgrade Reagent to `0.8.1`

### PR DESCRIPTION
**Pull request by Deraen**
TODO: Run shadow-cljs or figwheel-main tests with advanced compilation because this is probably currently missing some hints.

### CODE REVIEW

File: src/reagent/impl/batching.cljs [hunk 1]
```diff
@@ -37,7 +37,7 @@
   ;; are rendered before children
   (.sort a compare-mount-order)
   (dotimes [i (alength a)]
-    (let [c (aget a i)]
+    (let [^js/React.Component c (aget a i)]
```
Comment (lins05) [inline src/reagent/impl/batching.cljs]: I guess this is the trick that fixes the advanced compile bug I see in https://github.com/reagent-project/reagent/issues/449#issuecomment-554625425 ? I wonder how could non-shadow-cljs tools work without this?

Comment (Deraen) [reply src/reagent/impl/batching.cljs]: https://clojurescript.org/guides/externs
https://github.com/cljsjs/packages/blob/master/react/resources/cljsjs/react/common/react.ext.js#L149
https://shadow-cljs.github.io/docs/UsersGuide.html#_why_not_use_cljsjs

Comment (lins05) [reply src/reagent/impl/batching.cljs]: I see, so other tools would use the externs for react because it's bundled in cljsjs, while shadow-cljs can't make use of it. Thanks for the links!
